# Copyright 2023 Matteo Pagliardini, Amirkeivan Mohtashami, Francois Fleuret, Martin Jaggi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import torch
import distributed
import models

def none_or_str(value):
    if value == 'None':
        return None
    return value

def none_or_int(value):
    if value == 'None':
        return None
    return int(value)

def none_or_float(value):
    if value == 'None':
        return None
    return float(value)

def parse_args(base_parser, args, namespace):
    parser = base_parser
    # General training params
    parser.add_argument('--batch_size', default=128, type=int)
    parser.add_argument('--acc_steps', default=4, type=int)
    parser.add_argument('--seed', default=2, type=int)
    parser.add_argument('--device', default='cuda:0', type=str)
    parser.add_argument('--iterations', default=48000, type=int)
    parser.add_argument('--lr', default=1e-3, type=float)
    parser.add_argument('--warmup_percent', default=0.05, type=float)
    parser.add_argument('--weight_decay', default=1e-2, type=float)
    parser.add_argument('--beta1', default=0.9, type=float)
    parser.add_argument('--beta2', default=0.95, type=float)
    parser.add_argument('--scheduler', default='cos', choices=['linear', 'cos', 'none'])
    parser.add_argument('--opt', default='adamw', choices=['adamw', 'sgd'])
    parser.add_argument('--eval_freq', default=500, type=int) # in iterations
    parser.add_argument('--results_base_folder', default="./exps", type=str)
    parser.add_argument('--grad_clip', default=0.0, type=float) # default value is 1.0 in NanoGPT
    # Dataset params
    parser.add_argument('--dataset', default='pg19', choices=['pg19', 'owt2', 'hellaswag', 'deepmind_math', 'piqa', 'arc_easy', 'boolq', 'medqa', 'biology', 'chemistry'])
    parser.add_argument('--vocab_size', default=50304, type=int)
    parser.add_argument('--data_in_ram', action='store_true')
    # Model params
    parser.add_argument('--model', default='residual', choices=models.registered_models())
    parser.add_argument('--use_pretrained', default="none", type=str) # 'none', 'gpt-2' or a path to the pretraind model
    parser.add_argument('--dropout', default=0.2, type=float)
    parser.add_argument('--n_head', default=12, type=int)
    parser.add_argument('--n_layer', default=24, type=int) # depths in att + ff blocks
    parser.add_argument('--n_embd', default=768, type=int) # embedding size / hidden size ... 
    parser.add_argument('--sequence_length', default=256, type=int)
    parser.add_argument('--dtype', default="torch.bfloat16", type=str)
    parser.add_argument('--bias', default=False, type=bool)
    parser.add_argument('--no_compile', action='store_true') # if true then model is not compiled 
    parser.add_argument('--run_prefix', default=None, type=str, required=False) # is added before the autogenerated experiment name
    parser.add_argument('--exp_name', default=None, type=str, required=False) # use this name instead of autogenerated name
    # DenseFormer
    parser.add_argument('--increase_T_every', default=2, type=int)
    parser.add_argument('--dilation_factor', default=1, type=int)
    # Hybrid + Long Short
    parser.add_argument('--alphas_mean', default=1.0, type=float)
    parser.add_argument('--alphas_std', default=0.0, type=float)
    parser.add_argument('--alphas_train', action='store_true')
    parser.add_argument('--skipattn', action='store_true')
    parser.add_argument('--depthLN', action='store_true')
    parser.add_argument('--alphas_clamp', default=True, type=bool)
    parser.add_argument('--l1_regularizer_lamda', default=0.0, type=float)
    parser.add_argument('--binary_regularizer_lamda', default=0.0, type=float)
    parser.add_argument('--alphas_init_list', nargs='+', type=float, default=None)
    # EE
    parser.add_argument('--resume', default=None, type=str)
    parser.add_argument("--ee_training", action="store_true", default=False)
    parser.add_argument('--threshold', default=1.5, type=float)
    # MATH
    parser.add_argument('--mask_questions',  action='store_true', default=False,
                        help='Mask question tokens in the loss (answer-only training).')
    parser.add_argument('--pack_sequences',  action='store_true', default=True,
                        help='Pack multiple Q,A pairs per context window (paper setup). '
                            'If False, one Q,A pair per sequence (padded).')

    # ---------------------------------------------------------------------------
    # Hyper-connections config knobs
    #
    # Paste this block into parse_args() in my_config.py, alongside the other
    # model-param arguments.  All args are optional with sensible defaults so
    # existing launch scripts / checkpoints are completely unaffected.
    #
    # hc_disable=True  →  hyper-connections are a no-op (plain residual), useful
    #                      for ablations without changing any other code.
    # ---------------------------------------------------------------------------

    # --- Core HC ---
    parser.add_argument('--hc_num_streams', default=1, type=int,
                    help='Number of HC residual streams. 1 = standard residual (no-op).')
    parser.add_argument('--hc_num_fracs', default=1, type=int,
                    help='Number of HC stream fractions.')
    parser.add_argument('--hc_disable', action='store_true', default=False,
                    help='Disable hyper-connections entirely (plain residual).')

    # --- mHC (mhc) ---
    parser.add_argument('--mhc', action='store_true', default=False,
                    help='Enable multi-head hyper-connections.')
    parser.add_argument('--sinkhorn_iters', default=10, type=int)
    parser.add_argument('--sinkhorn_tau', default=0.05, type=float)
    parser.add_argument('--mhc_h_res_proj', default='sinkhorn', type=str,
                    choices=['sinkhorn', 'identity'])
    parser.add_argument('--ns_steps', default=5, type=int,
                    help='Newton-Schulz steps for orthogonalisation.')
    parser.add_argument('--ns_eps', default=1e-7, type=float)
    parser.add_argument('--ns_coeffs', nargs=3, type=float, default=[3.0, -3.2, 1.2],
                    help='Newton-Schulz polynomial coefficients (3 values).')
    parser.add_argument('--mhc_residual_identity_mix', action='store_true', default=False)
    parser.add_argument('--mhc_residual_alpha', default=0.01, type=float)

    # --- Value residual ---
    parser.add_argument('--v_residual', action='store_true', default=False,
                    help='Enable value residual in attention (lamb1/lamb2 learnable scalars).')
    parser.add_argument('--v_residual_lamb_lr', default=1e-2, type=float,
                    help='Learning rate for value-residual lamb parameters.')

    # logging params (WandB)
    parser.add_argument("--wandb", action="store_true", default=False)
    #parser.add_argument('--wandb', default=False, type=bool) # whether to use wandb or not
    parser.add_argument('--wandb_project', default="proj", type=str)
    # Distributed args
    parser.add_argument('--distributed_backend', default="nccl", type=none_or_str, required=False,
                        choices=distributed.registered_backends())  # distributed backend type
    parser.add_argument('--positional_encoder', default="rotary", type=str, required=False,
                        choices=models.positional_encoders.registered_encoders())  # distributed backend type
    parser.add_argument('--lm_cache', default="none", type=str, required=False,
                        choices=models.caches.registered_caches())  # distributed backend type
    parser.add_argument('--mem_cache_size', default=None, type=int, required=False)
    parser.add_argument('--cache_topk', default=1, type=int, required=False)
    parser.add_argument('--cache_selection_method', default="per_token_and_head", type=str, required=False,)  # distributed backend type
    parser.add_argument('--cache_indexing_scheme', default="by_total", type=str, required=False,)  # distributed backend type
    parser.add_argument('--pos_jump_freq', default=None, type=none_or_int, required=False)
    parser.add_argument('--pos_jump_schedule', default=None, type=str, required=False)  # distributed backend type
    parser.add_argument('--eval_seq_length', default=None, type=none_or_int, required=False)
    parser.add_argument('--eval_sample_size', default=None, type=none_or_int, required=False)
    parser.add_argument('--attention_window_length', default=None, type=int, required=False)
    parser.add_argument('--track_cache_attention', action='store_true') # if true then model is not compiled 
    parser.add_argument('--allow_cache_during_training', action='store_true') # if true then model is not compiled
    parser.add_argument('--optimization_process', default=None, type=str, required=False,
                        choices=["base"])  # distributed backend type 
    parser.add_argument('--total_sequence_length', default=None, type=int, required=False)
    parser.add_argument('--save_checkpoint_freq', default=1000, type=int, required=False)

    args = parser.parse_args(args, namespace)
    
    if args.exp_name is None:
        special_name_handle_fields = {"model", "lr", "batch_size", 
                                      "acc_steps", "seed", "exp_name", 
                                      "wandb", "wandb_project",
                                      "run_prefix", "distributed_backend", "config_format",
                                      "sequence_length"}
        overriden_values = []
        for key in vars(args):
            if key in special_name_handle_fields:
                continue
            if getattr(args, key) != parser.get_default(key):
                overriden_values.append((key, getattr(args, key)))
        chunk_len = 10
        overriden_values_str_parts = []
        for chunk_id in range(0, len(overriden_values), chunk_len):
            overriden_values_str = "_".join(["{}={}".format(key, value) for key, value in overriden_values[chunk_id:chunk_id+chunk_len]])
            overriden_values_str_parts.append(overriden_values_str)
        overriden_values_str = "/".join(overriden_values_str_parts)
        exp_name = ""
        if args.run_prefix is not None:
            exp_name += f"{args.run_prefix}_"
        exp_name += f"{args.model}_lr{args.lr}_bs{args.batch_size}x{args.acc_steps}_seqlen{args.sequence_length}/{overriden_values_str}_seed={args.seed}"
        args.exp_name = exp_name

    if args.dtype == "torch.bfloat16":
        args.dtype = torch.bfloat16
    elif args.dtype == "torch.float16":
        args.dtype = torch.float16

    
    return args
